name: "Generate Download Page"
author: "Kungfu Trader"
description: "Generate Download Page When Merged"
inputs:
  apiKey:
    description: "airtable openapi token"
    required: false
  bucket-prebuilt:
    description: "S3 Bucket used as release area of prebuilt binaries"
    default: 'kungfu-prebuilt'
    required: false
  bucket-release:
    description: "S3 Bucket used as release area of prebuilt binaries"
    default: 'kungfu-releases'
    required: false
  airtable-baseid:
    description: "airtable base for pr issues"
    default: 'appAdi5zFFEsCzmEM'
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
