name: "Generate Download Page"
author: "Kungfu Trader"
description: "Generate Download Page When Merged"
inputs:
  apiKey:
    description: "secrets.AIRTABLE_API_KEY"
    required: false
  bucket-prebuilt:
    description: "S3 Bucket used as release area of prebuilt binaries"
    required: false
  bucket-release:
    description: "S3 Bucket used as release area of prebuilt binaries"
    required: false
  airtable-baseid:
    description: "airtable base for pr issues"
    default: 'appAdi5zFFEsCzmEM'
    required: false
outputs:
  has_notes:
    description: "Whether the notes exists or not."

runs:
  using: "node16"
  main: "dist/index.js"
